export const CARDS_DATA_LOAD_START = 'CARDS_DATA_LOAD_START';
export const CARDS_DATA_LOAD_END = 'CARDS_DATA_LOAD_END';

export const CARDS_GET_RANDOM_ITEMS = 'CARDS_GET_RANDOM_ITEMS';

export const CARDS_ADD_ITEMS = 'CARDS_ADD_ITEMS';
export const CARDS_REMOVE_ITEMS = 'CARDS_REMOVE_ITEMS';

export const CARDS_CHECK_SET_RIGHT = 'CARDS_CHECK_SET_RIGHT';
export const CARDS_CHECK_SET_WRONG = 'CARDS_CHECK_SET_WRONG';

export const CARDS_SHOW_TIP = 'CARDS_SHOW_TIP';