export const CARDS_DATA_LOAD_START = 'CARDS_DATA_LOAD_START';
export const CARDS_DATA_LOAD_END = 'CARDS_DATA_LOAD_END';

export const CARDS_GET_RANDOM_ITEMS = 'CARDS_GET_RANDOM_ITEMS';

export const CARDS_ADD_ITEMS = 'CARDS_ADD_ITEMS';
export const CARDS_REMOVE_ITEMS = 'CARDS_REMOVE_ITEMS';
export const CARDS_CHECK_SET = 'CARDS_CHECK_SET';
